### ISSUE TITLE
Compile error on 1.1.3 in Strict mode

### ISSUE THREAD

**Issue by trevorbattle** [braydenanderson2014/C-Arduino-Libraries#94]
Using Hashtable and SimpleVector from platformio, which resolves latest to Hashtable@1.1.3 and SimpleVector@1.0.8.

Platform is esp32dev/latest. Framework is arduino.

Compile fails at line 506 in Hashtable.h

The error is:
`return-statement with no value, in function returning 'String' [-fpermissive]`

The line is:
 `return; // Return null if the key is not found`

Works if I force older versions, ie:

Works:
` lib_deps = braydenanderson2014/SimpleVector@1.0.7, braydenanderson2014/Hashtable@1.1.3-BETA`

Fails:
`  lib_deps = braydenanderson2014/SimpleVector, braydenanderson2014/Hashtable`

**Comment by braydenanderson2014** [comment]
Apologies. This issue was already resolved in the main repository. It appears I forgot to update the ArduinoHashtable Repository with the fix. I will get that updated asap. Thank you for reporting this issue.

**Comment by braydenanderson2014** [comment]
Update has been pushed. Idk if it will work since i deleted the original update and then reinstated it with the modified header. So if it does not work, let me know and ill push Hashtable to the next update block. Thank you for bringing the issue to my attention.

**Comment by trevorbattle** [comment]
I'm still getting the old version through Platformio, so it might need a bump. 

I'm also still getting the spurious "Arduino" dependency, but I feel like I've reported that before somewhere else. (This package names "arduino" as a dependency but that isn't a proper item in the registry so it guesses a few odd choices and picks the first one and warns of ambiguity)

```
Library Manager: SimpleVector@1.0.8 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing Arduino @ *
Library Manager: Warning! More than one package has been found by Arduino @ * requirements:
Library Manager:  - mbed-aluqard/arduino@0.0.0+sha.3b83fc30bbdf
Library Manager:  - mbed-team2/Arduino@0.0.0+sha.d96590319bcf
Library Manager:  - mbed-eduardog26/Arduino@0.0.0+sha.abbc3308dfa1
Library Manager:  - mbed-rahulsitaram/Arduino@0.0.0+sha.d0b32a4209f0
Library Manager:  - mbed-thechrisyd/Arduino@0.0.0+sha.272d0276d474
Library Manager:  - mbed-gastonfeng/arduino@0.0.0-alpha+sha.b000674ff8b3
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (shown above) to avoid name conflicts
```

Tx!

**Comment by braydenanderson2014** [comment]
Ok I will push to the next version so Arduino will properly gather the version. As for the Arduino dependency, I am aware it does that. But since it doesn't have any impact I decided to leave it alone. Give me a few hours and I should have everything working again.

**Comment by braydenanderson2014** [comment]
Hello, I have finally fixed the issue. I had forgotten to publish the Platformio version. I had only updated the Arduino version. This has now been fixed. Both versions have been updated and should now officially be up to date. If you run into anymore issues, please do not hesitate to reach out. All issues become a learning experience :) 

Thank you!
